# vim:set ft=tmux:
%hidden MODULE_NAME="user"

set -ogq @gruvbox_user_icon " "
set -ogqF @gruvbox_user_color "#{E:@thm_blue}"
set -ogq @gruvbox_user_text " #{?USER,#{USER},#(whoami)}"

source -F "#{d:current_file}/../utils/status_module.conf"
